import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F5F7",
    alignItems: "center",
    justifyContent: "center",
  },
  headerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#2E7D32",
    paddingVertical: 50,
    elevation: 5,
  },
  title: {
    fontSize: 35,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    letterSpacing: 2,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: "300",
    color: "#D5E8D4",
    textAlign: "center",
    marginTop: 5,
  },
  formContainer: {
    flex: 2,
    width: "90%",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginTop: -30,
    elevation: 10,
    alignItems: "center",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    backgroundColor: "#F9F9F9",
    borderRadius: 10,
    width: "100%",
    padding: 15,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    elevation: 5,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 5,
      },
    }),
  },
  countryCodeButton: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#F9F9F9",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    marginRight: 10,
  },
  countryCodeText: {
    fontSize: 16,
    color: "#333333",
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: "#333333",
  },
  submitButton: {
    backgroundColor: "#388E3C",
    paddingVertical: 15,
    borderRadius: 10,
    width: "100%",
    alignItems: "center",
    marginTop: 15,
  },
  submitText: {
    fontSize: 18,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  countryItem: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  countryItemText: {
    fontSize: 16,
    color: "#333333",
  },
  backButton: {
    backgroundColor: "#E0E0E0",
    paddingVertical: 10,
    borderRadius: 10,
    width: "100%",
    alignItems: "center",
    marginTop: 15,
  },
  backText: {
    fontSize: 16,
    color: "#333333",
  },
  orText: {
    fontSize: 16,
    color: "#888888",
    marginVertical: 20,
  },
  socialButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F5F7",
    borderRadius: 10,
    width: "100%",
    paddingVertical: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  socialButtonText: {
    fontSize: 16,
    marginLeft: 10,
    color: "#333333",
  },
  supportContainer: {
    marginTop: 20,
  },
  supportText: {
    fontSize: 14,
    color: "#388E3C",
    textAlign: "center",
    textDecorationLine: "underline",
  },
});
