import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  container: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  scrollViewContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 20 : 40,
  },
  headerContainer: {
    marginBottom: 30,
    alignItems: "center",
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: "600",
    color: "#333",
    textAlign: "center",
    marginBottom: 8,
    marginTop: 40,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    color: "#2E7D32",
    textAlign: "center",
    marginBottom: 8,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif-medium",
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  progressBarContainer: {
    marginBottom: 30,
    width: "100%",
  },
  formContainer: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 24,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 16,
    elevation: 3,
    width: "100%",
    alignSelf: "center",
    borderWidth: Platform.OS === "ios" ? 1 : 0,
    borderColor: "rgba(0,0,0,0.05)",
  },
  fieldTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 16,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif-medium",
  },
  input: {
    width: "100%",
    height: 56,
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
    paddingHorizontal: 16,
    fontSize: 16,
    color: "#333",
    borderWidth: 1,
    borderColor: "#E9ECEF",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  inputError: {
    borderColor: "#D32F2F",
  },
  multilineInput: {
    height: 120,
    paddingTop: 16,
    paddingBottom: 16,
    textAlignVertical: "top",
  },
  dateText: {
    fontSize: 16,
    color: "#333",
    paddingVertical: 16,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  errorText: {
    color: "#D32F2F",
    fontSize: 14,
    marginTop: 8,
    marginLeft: 4,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  sexButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  sexButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: "#F8F9FA",
    borderWidth: 1,
    borderColor: "#E9ECEF",
    alignItems: "center",
    justifyContent: "center",
  },
  selectedSexButton: {
    backgroundColor: "#E8F5E9",
    borderColor: "#4CAF50",
  },
  sexButtonText: {
    fontSize: 16,
    color: "#666",
    fontWeight: "500",
    fontFamily: Platform.select({
      ios: "System",
      android: "sans-serif-medium",
    }),
  },
  selectedSexButtonText: {
    color: "#2E7D32",
  },
  submitButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 18,
    borderRadius: 16,
    width: "100%",
    marginTop: 24,
    shadowColor: "#4CAF50",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 4,
  },
  submitButtonDisabled: {
    backgroundColor: "#A5D6A7",
  },
  submitText: {
    fontSize: 18,
    color: "#FFF",
    fontWeight: "600",
    textAlign: "center",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif-medium",
  },
  inputAccessory: {
    height: 45,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    borderTopWidth: 1,
    borderTopColor: "#E9ECEF",
    paddingHorizontal: 8,
  },
  accessoryButton: {
    padding: 8,
  },
  accessoryButtonText: {
    color: "#4CAF50",
    fontSize: 16,
    fontWeight: "600",
  },
  datePickerContainer: {
    backgroundColor: "#FFF",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    borderTopWidth: 1,
    borderTopColor: "#E9ECEF",
  },
  datePickerButton: {
    padding: 16,
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#E9ECEF",
  },
  datePickerButtonText: {
    color: "#4CAF50",
    fontSize: 16,
    fontWeight: "600",
  },
});
